import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {CameraFeed} from './camera-feed';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={styles.description_title}>Web API Camera with React and Nextjs! &nbsp; </h1>
        </div>

        <div className={styles.description}>
            <p>In this app you will be able to interact with the camera api and select one of the few avaialble cameras from given device.</p>
        </div>

        <div >
          <CameraFeed  sendFile={(base64Image: string) => console.log('file as base64:', base64Image)} />
        </div>
      </main>
    </>
  )
}
